name: 'Plugin Machine Plugin Builder'
description: 'Build installable ZIP files for your WordPress Plugin'
inputs:
  PLUGIN_MACHINE_TOKEN:
    description: 'Plugin Machine Token'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  PLUGIN_DIR:
    description: Directory with plugin
    required: false
  COMMENT_PR:
    description: If a link to ZIP should be added to PR
    required: false



outputs:
  upload:
    description: Upload details


runs:
  using: 'node16'
  main: 'dist/index.js'
