name: 'Plugin Machine Plugin Builder'
description: 'Build installable ZIP files for your WordPress Plugin'
inputs:
  token:
    description: 'Plugin Machine Token'
    required: true
  pluginDir:
    description: Directory with plugin
    required: false
  commentPr:
    description: If a link to ZIP should be added to PR
    required: false
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true


outputs:
  upload:
    description: Upload details


runs:
  using: 'node16'
  main: 'dist/index.js'
