name: 'Plugin Machine Plugin Builder'
description: 'Build installable ZIP files for your WordPress Plugin'
inputs:
  token:  # id of input
    description: 'Plugin Machine API Token'
    required: true
  path:  # id of input
    description: Root directory of plugin. Probably ${{ github.workspace }}
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
