name: 'Plugin Machine Plugin Builder'
description: 'Build installable ZIP files for your WordPress Plugin'
inputs:
  token:  # id of input
    description: 'Plugin Machine API Token'
    required: true
  path:  # id of input
    description: Root directory of plugin. Probably ${{ github.workspace }}
    required: true
outputs:
  zipFile: # output will be available to future steps
    description: 'Local path to zip file'
  zipDownload:
    description: 'Path to download uploaded zip'
runs:
  using: 'node16'
  main: 'dist/index.js'
